# Generated by Django 5.1.2 on 2025-06-18 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('ic_number', models.CharField(max_length=20, unique=True, verbose_name='IC Number')),
                ('class_name', models.CharField(max_length=50, verbose_name='Class')),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6')], max_length=1, verbose_name='Semester')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('program', models.CharField(choices=[('DCS', 'Diploma in Computer Science'), ('DIA', 'Diploma in Accounting'), ('DEC', 'Diploma in English Communication'), ('DCD', 'Diploma in Creative Digital Media')], max_length=3, verbose_name='Program')),
                ('academic_advisor', models.CharField(max_length=100, verbose_name='Academic Advisor Name')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('case_type', models.CharField(choices=[('attendance', 'Late Attendance'), ('dress_code', 'Dress Code Violation'), ('smoking', 'Smoking on Campus'), ('academic_dishonesty', 'Academic Dishonesty'), ('fighting', 'Fighting'), ('vandalism', 'Vandalism'), ('disrespect', 'Disrespectful Behavior'), ('unauthorized_access', 'Unauthorized Access'), ('substance_abuse', 'Substance Abuse'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('serious', 'Serious')], default='minor', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('witnesses', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_cases', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Disciplinary Case',
                'verbose_name_plural': 'Disciplinary Cases',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.disciplinarycase')),
            ],
            options={
                'verbose_name': 'Case Status History',
                'verbose_name_plural': 'Case Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.disciplinarycase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=20, unique=True)),
                ('month', models.CharField(max_length=20)),
                ('total_cases', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('resolved_cases', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Login',
                'verbose_name_plural': 'Student Logins',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JDK Supervisor',
                'verbose_name_plural': 'JDK Supervisors',
            },
        ),
    ]
