# Generated by Django 5.1.2 on 2025-06-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='location',
        ),
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='disciplinarycase',
            name='witnesses',
        ),
    ]
